/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author M.Adhitya Yusuf
 */
import backend.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class FrmTransaksi extends javax.swing.JFrame {
    private ArrayList<Kendaraan> listKendaraan = new ArrayList<>();
    private ArrayList<Integer> listIdPelanggan = new ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmTransaksi.class.getName());
    
    /**
     * Creates new form FrmTransaksi
     */
    public FrmTransaksi() {
        initComponents();
        loadDataCombo();
        tampilkanDataTabel();
        kosongkanForm();
    }
    
    public void kosongkanForm() {
        txtIdTransaksi.setText("0");
        txtLama.setText("");
        lblTotal.setText("Rp 0");
        lblInfoKendaraan.setText("-");
        txtTanggal.setText(""); // Kosongkan field tanggal
        if (cmbPelanggan.getItemCount() > 0) cmbPelanggan.setSelectedIndex(0);
        if (cmbKendaraan.getItemCount() > 0) cmbKendaraan.setSelectedIndex(0);
    }
    
    public void loadDataCombo() {
        // Load Pelanggan
        cmbPelanggan.removeAllItems();
        listIdPelanggan.clear();
        ResultSet rs = DBHelper.selectQuery("SELECT * FROM pelanggan");
        try {
            while(rs.next()) {
                cmbPelanggan.addItem(rs.getString("nama"));
                listIdPelanggan.add(rs.getInt("id_pelanggan"));
            }
        } catch(Exception e) {}

        // Load Kendaraan (Polimorfisme: Mobil & Motor masuk ke listKendaraan)
        cmbKendaraan.removeAllItems();
        listKendaraan.clear();
        
        // Hanya tampilkan kendaraan yang tersedia agar tidak double booking
        rs = DBHelper.selectQuery("SELECT * FROM kendaraan WHERE status = 'Tersedia'");
        try {
            while(rs.next()) {
                Kendaraan k;
                String jenis = rs.getString("jenis");
                
                // --- PENERAPAN POLYMORPHISM ---
                if(jenis.equalsIgnoreCase("Mobil")) {
                    k = new Mobil(); // Object Mobil
                } else {
                    k = new Motor(); // Object Motor
                }
                
                k.setId(rs.getInt("id_kendaraan")); 
                k.setMerk(rs.getString("merk"));
                k.setNopol(rs.getString("nopol"));
                k.setHargaPerHari(rs.getDouble("harga_per_hari"));
                
                listKendaraan.add(k);
                cmbKendaraan.addItem(rs.getString("merk") + " - " + rs.getString("nopol"));
            }
        } catch(Exception e) {}
    }
    
    public void tampilkanDataTabel() {
        String[] kolom = {"ID", "Penyewa", "Kendaraan", "Tgl", "Total"};
        DefaultTableModel model = new DefaultTableModel(null, kolom);
        
        ArrayList<Transaksi> list = new Transaksi().getAll();
        
        for(Transaksi t : list) {
            Object[] row = {
                t.getIdTransaksi(),
                t.getPelanggan().getNama(),
                t.getKendaraan().getMerk(), 
                t.getTanggalSewa(),
                t.getTotalBayar()
            };
            model.addRow(row);
        }
        tblTransaksi.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPelanggan = new javax.swing.JComboBox<>();
        cmbKendaraan = new javax.swing.JComboBox<>();
        lblInfoKendaraan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLama = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtIdTransaksi = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        txtTanggal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TRANSAKSI RENTAL");

        jLabel2.setText("Pilih Pelanggan");

        jLabel3.setText("Pilih Kendaraan");

        cmbPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKendaraanActionPerformed(evt);
            }
        });

        lblInfoKendaraan.setText("-");

        jLabel5.setText("Lama Sewa (Hari)");

        txtLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLamaActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung Total");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblTotal.setText("Rp 0");

        btnSimpan.setText("Simpan Transaksi");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        jLabel4.setText("ID Transaksi");

        txtIdTransaksi.setEnabled(false);
        txtIdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTransaksiActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal sewa");

        jLabel7.setText("Contoh isi: 2025-12-12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(188, 188, 188))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbKendaraan, 0, 130, Short.MAX_VALUE)
                                    .addComponent(txtLama)
                                    .addComponent(txtTanggal)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbPelanggan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblInfoKendaraan))
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTotal)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapus)))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfoKendaraan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(btnHitung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLamaActionPerformed

    private void cmbKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKendaraanActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        try {
            int indexK = cmbKendaraan.getSelectedIndex();
            int lama = Integer.parseInt(txtLama.getText());
            
            if(indexK >= 0 && indexK < listKendaraan.size()) {
                Kendaraan k = listKendaraan.get(indexK);
                double total = k.hitungTotalBayar(lama);
                
                lblTotal.setText("Rp " + String.valueOf(total));
                lblInfoKendaraan.setText(k.getInfoSpesifik());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka lama sewa yang valid!");
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            Transaksi t = new Transaksi();
            
            int idxPel = cmbPelanggan.getSelectedIndex();
            int idxKen = cmbKendaraan.getSelectedIndex();

            if (idxPel >= 0 && idxKen >= 0) {
                // Set Pelanggan
                Pelanggan p = new Pelanggan();
                p.setIdPelanggan(listIdPelanggan.get(idxPel));
                t.setPelanggan(p);

                // Set Kendaraan
                Kendaraan k = listKendaraan.get(idxKen);
                t.setKendaraan(k);

                // --- PERBAIKAN TANGGAL ---
                // Ambil tanggal dari input user, bukan otomatis hari ini
                String inputTanggal = txtTanggal.getText();
                if(inputTanggal.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Tanggal tidak boleh kosong!");
                    return;
                }
                t.setTanggalSewa(inputTanggal); 
                
                t.setLamaSewa(Integer.parseInt(txtLama.getText()));
                
                // Ambil total bayar (bersihkan string "Rp ")
                String totalStr = lblTotal.getText().replace("Rp ", "").trim();
                if(totalStr.equals("0")) {
                    JOptionPane.showMessageDialog(this, "Klik Hitung Total dulu!");
                    return;
                }
                t.setTotalBayar(Double.parseDouble(totalStr));

                t.save();
                
                kosongkanForm();
                tampilkanDataTabel();
                loadDataCombo(); // Refresh data kendaraan tersedia
                JOptionPane.showMessageDialog(this, "Transaksi Berhasil Disimpan!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtIdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTransaksiActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblTransaksi.getModel();
        int row = tblTransaksi.getSelectedRow();
        
        if (row >= 0) {
            Transaksi t = new Transaksi();
            int id = Integer.parseInt(model.getValueAt(row, 0).toString());
            t.setIdTransaksi(id);
            t.delete();
            
            kosongkanForm();
            tampilkanDataTabel();
            loadDataCombo(); // Refresh agar kendaraan yang dihapus muncul lagi di combo
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel dulu!");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblTransaksi.getModel();
        int row = tblTransaksi.getSelectedRow();
        txtIdTransaksi.setText(model.getValueAt(row, 0).toString());
        // Jika Anda ingin menampilkan tanggal juga saat diklik:
        // txtTanggal.setText(model.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmTransaksi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbKendaraan;
    private javax.swing.JComboBox<String> cmbPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfoKendaraan;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtIdTransaksi;
    private javax.swing.JTextField txtLama;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}